spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    name: gadget
    url: jdbc:log4jdbc:mysql://192.168.17.28:3306/gadget
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy

wechat:
  mp:
    appId: wx7a9424c572091593
    secret: d4624c36b6795d1d99dcf0547af5443d
    token: 2MLcyFqJmrQY6kCxzNsLAilFN1b9jrKF

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml

